# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc/zedboard_v2.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_axi_periph_0/system_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_periph_0 || ORIG_REF_NAME==system_axi_periph_0} -quiet] -quiet

# IP: bd/system/ip/system_fifo_mm2s_0/system_fifo_mm2s_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fifo_mm2s_0 || ORIG_REF_NAME==system_fifo_mm2s_0} -quiet] -quiet

# IP: bd/system/ip/system_fifo_s2mm_0/system_fifo_s2mm_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fifo_s2mm_0 || ORIG_REF_NAME==system_fifo_s2mm_0} -quiet] -quiet

# IP: bd/system/ip/system_ov7670_decode_stream_0_0/system_ov7670_decode_stream_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ov7670_decode_stream_0_0 || ORIG_REF_NAME==system_ov7670_decode_stream_0_0} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ov7670_pclk_0/system_rst_ov7670_pclk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_ov7670_pclk_0 || ORIG_REF_NAME==system_rst_ov7670_pclk_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_processing_system7_0_100M_0/system_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==system_rst_processing_system7_0_100M_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_vga_clk25_0/system_rst_vga_clk25_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_vga_clk25_0 || ORIG_REF_NAME==system_rst_vga_clk25_0} -quiet] -quiet

# IP: bd/system/ip/system_stream_to_vga_0_0/system_stream_to_vga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_stream_to_vga_0_0 || ORIG_REF_NAME==system_stream_to_vga_0_0} -quiet] -quiet

# IP: bd/system/ip/system_vdma_mm2s_0/system_vdma_mm2s_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_vdma_mm2s_0 || ORIG_REF_NAME==system_vdma_mm2s_0} -quiet] -quiet

# IP: bd/system/ip/system_vdma_mm2s_intercon_0/system_vdma_mm2s_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_vdma_mm2s_intercon_0 || ORIG_REF_NAME==system_vdma_mm2s_intercon_0} -quiet] -quiet

# IP: bd/system/ip/system_vdma_s2mm_0/system_vdma_s2mm_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_vdma_s2mm_0 || ORIG_REF_NAME==system_vdma_s2mm_0} -quiet] -quiet

# IP: bd/system/ip/system_vdma_s2mm_intercon_0/system_vdma_s2mm_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_vdma_s2mm_intercon_0 || ORIG_REF_NAME==system_vdma_s2mm_intercon_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_ov7670_controller_0_0/system_ov7670_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ov7670_controller_0_0 || ORIG_REF_NAME==system_ov7670_controller_0_0} -quiet] -quiet

# IP: bd/system/ip/system_debounce_0_0/system_debounce_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_debounce_0_0 || ORIG_REF_NAME==system_debounce_0_0} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_blk_mem_gen_0_0/system_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_blk_mem_gen_0_0 || ORIG_REF_NAME==system_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/system/ip/system_color_detector_0_2/system_color_detector_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_color_detector_0_2 || ORIG_REF_NAME==system_color_detector_0_2} -quiet] -quiet

# IP: bd/system/ip/system_balls_overlay_0_0/system_balls_overlay_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_balls_overlay_0_0 || ORIG_REF_NAME==system_balls_overlay_0_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_2/system_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_2 || ORIG_REF_NAME==system_auto_pc_2} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_1 || ORIG_REF_NAME==system_auto_pc_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_cc_0/system_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_0 || ORIG_REF_NAME==system_auto_cc_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: bd/system/ip/system_fifo_mm2s_0/system_fifo_mm2s_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fifo_mm2s_0 || ORIG_REF_NAME==system_fifo_mm2s_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_fifo_mm2s_0/system_fifo_mm2s_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fifo_mm2s_0 || ORIG_REF_NAME==system_fifo_mm2s_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_fifo_mm2s_0/system_fifo_mm2s_0_ooc.xdc

# XDC: bd/system/ip/system_fifo_s2mm_0/system_fifo_s2mm_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fifo_s2mm_0 || ORIG_REF_NAME==system_fifo_s2mm_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_fifo_s2mm_0/system_fifo_s2mm_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fifo_s2mm_0 || ORIG_REF_NAME==system_fifo_s2mm_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_fifo_s2mm_0/system_fifo_s2mm_0_ooc.xdc

# XDC: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_rst_ov7670_pclk_0/system_rst_ov7670_pclk_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ov7670_pclk_0 || ORIG_REF_NAME==system_rst_ov7670_pclk_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_rst_ov7670_pclk_0/system_rst_ov7670_pclk_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ov7670_pclk_0 || ORIG_REF_NAME==system_rst_ov7670_pclk_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_rst_ov7670_pclk_0/system_rst_ov7670_pclk_0_ooc.xdc

# XDC: bd/system/ip/system_rst_processing_system7_0_100M_0/system_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==system_rst_processing_system7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_rst_processing_system7_0_100M_0/system_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==system_rst_processing_system7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_rst_processing_system7_0_100M_0/system_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/system/ip/system_rst_vga_clk25_0/system_rst_vga_clk25_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_vga_clk25_0 || ORIG_REF_NAME==system_rst_vga_clk25_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_rst_vga_clk25_0/system_rst_vga_clk25_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_vga_clk25_0 || ORIG_REF_NAME==system_rst_vga_clk25_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_rst_vga_clk25_0/system_rst_vga_clk25_0_ooc.xdc

# XDC: bd/system/ip/system_vdma_mm2s_0/system_vdma_mm2s_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_vdma_mm2s_0 || ORIG_REF_NAME==system_vdma_mm2s_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_vdma_mm2s_0/system_vdma_mm2s_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_vdma_mm2s_0 || ORIG_REF_NAME==system_vdma_mm2s_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_vdma_mm2s_0/system_vdma_mm2s_0_ooc.xdc

# XDC: bd/system/ip/system_vdma_s2mm_0/system_vdma_s2mm_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_vdma_s2mm_0 || ORIG_REF_NAME==system_vdma_s2mm_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_vdma_s2mm_0/system_vdma_s2mm_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_vdma_s2mm_0 || ORIG_REF_NAME==system_vdma_s2mm_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_vdma_s2mm_0/system_vdma_s2mm_0_ooc.xdc

# XDC: bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_ooc.xdc

# XDC: bd/system/ip/system_blk_mem_gen_0_0/system_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_2/system_auto_pc_2_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_0/system_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_0 || ORIG_REF_NAME==system_auto_cc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_auto_cc_0/system_auto_cc_0_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: bd/system/system_ooc.xdc
